from __future__ import annotations

import re

import pytest
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import LargeBinary
from sqlalchemy import MetaData
from sqlalchemy import Table
from sqlalchemy import insert
from sqlalchemy import select
from sqlalchemy.testing import fixtures

from test._project_test_helpers import cleanup_objects


class TestProjectKnownLimits(fixtures.TestBase):
    __backend__ = True

    def test_identity_ddl_capability(self, engine):
        """Probe native IDENTITY DDL; dialect keeps supports_identity_columns=False."""
        ddl = (
            "create table pc_lim_id_probe ("
            "id int generated by default as identity, "
            "n varchar(10))"
        )
        with engine.connect() as connection:
            cleanup_objects(connection, "pc_lim_id_probe")
            try:
                connection.exec_driver_sql(ddl)
                connection.commit()
            except Exception as exc:
                connection.rollback()
                assert re.search(r"(?i)generated|identity|YAS-", str(exc)), (
                    "unexpected error creating IDENTITY table: %s" % exc
                )
                return

            try:
                connection.exec_driver_sql(
                    "insert into pc_lim_id_probe (n) values ('x')"
                )
                connection.commit()
                row = connection.exec_driver_sql(
                    "select id, n from pc_lim_id_probe where n = 'x'"
                ).fetchone()
                assert row is not None
                assert row[0] is not None
                assert int(row[0]) >= 1
            finally:
                cleanup_objects(connection, "pc_lim_id_probe")

    def test_largebinary_null_byte_round_trip(self, engine):
        """Verifies yaspy binds bytes with embedded NUL via PyBytes_GET_SIZE length."""
        table_name = "pc_lim_blob_probe"
        metadata = MetaData()
        table = Table(
            table_name,
            metadata,
            Column("id", Integer, primary_key=True),
            Column("payload", LargeBinary),
        )
        payload = b"abc\x00xyz"

        with engine.connect() as connection:
            cleanup_objects(connection, table_name)
            metadata.create_all(connection)
            connection.execute(insert(table), {"id": 1, "payload": payload})

            read_back = connection.execute(
                select(table.c.payload).where(table.c.id == 1)
            ).scalar()

            assert read_back == payload

            metadata.drop_all(connection)
            cleanup_objects(connection, table_name)
